version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: tucmc
      POSTGRES_PASSWORD: tucmc
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # web:
  #   build:
  #     context: .
  #     args:
  #       ENV_VARIABLE: ${ENV_VARIABLE}
  #       NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
  #   restart: always
  #   ports:
  #     - 3000:3000

volumes:
  postgres_data:
